version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.10
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:2.7.10
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test